CREATE TYPE public.github_webhook_event AS ENUM (
    'branch_protection_rule',
    'check_run',
    'check_suite',
    'code_scanning_alert',
    'commit_comment',
    'create',
    'delete',
    'deployment',
    'deployment_status',
    'deploy_key',
    'discussion',
    'discussion_comment',
    'fork',
    'gollum',
    'issues',
    'issue_comment',
    'label',
    'member',
    'membership',
    'meta',
    'milestone',
    'organization',
    'org_block',
    'package',
    'page_build',
    'project',
    'project_card',
    'project_column',
    'public',
    'pull_request',
    'pull_request_review',
    'pull_request_review_comment',
    'pull_request_review_thread',
    'push',
    'registry_package',
    'release',
    'repository',
    'repository_import',
    'repository_vulnerability_alert',
    'secret_scanning_alert',
    'star',
    'status',
    'team',
    'team_add',
    'watch',
    'workflow_job',
    'workflow_run',
    'unknown'
    );

CREATE TABLE public.webhook_cache
(
    delivery_id     UUID PRIMARY KEY            NOT NULL,
    event_type      public.github_webhook_event NOT NULL,
    created_at      TIMESTAMP                   NOT NULL DEFAULT NOW(),
    signature_256   TEXT                        NOT NULL,
    installation_id INTEGER,
    data            JSONB                       NOT NULL,
    sqs_message_id  TEXT
);

CREATE INDEX webhook_cache_created_at_idx ON public.webhook_cache (created_at);
CREATE INDEX webhook_cache_event_type_idx ON public.webhook_cache (event_type);
CREATE INDEX webhook_cache_sqs_message_id_idx ON public.webhook_cache (sqs_message_id);
