aws_gateway:
  mock: false
  region: us-west-2
  ciphertext_bucket: ${CIPHERTEXT_VAULT_S3_BUCKET}
tokenizer:
  secret_arn: ${TOKENIZER_SECRET_ARN}
jwt_manager:
  signing_keys_arn: ${SIGNING_KEYS_ARN}
