enableGlobalCache: true

defaultSemverRangePrefix: ~

logFilters:
  - level: discard
    pattern: require call ambiguous and unsound

nmHoistingLimits: none

nodeLinker: pnp

packageExtensions:
  "@aws-cdk/aws-lambda-nodejs@^1.138.1":
    dependencies:
      "@aws-cdk/aws-ec2": ^1.129.0
      "@aws-cdk/aws-iam": ^1.129.0
  "@docsearch/react@3.0.0-alpha.41":
    dependencies:
      "@algolia/client-search": ^4.11.0
  "@docusaurus/theme-search-algolia@2.0.0-beta.ff31de0ff":
    dependencies:
      prism-react-renderer: ^1.2.1
  "@material-ui/lab@^4.12.3":
    dependencies:
      "@material-ui/types": ^5.1.0
  "@types/http-proxy@*":
    dependencies:
      events: "*"
      url: "*"
  "@types/express-serve-static-core@*":
    peerDependenciesMeta:
      events:
        optional: true
      range-parser:
        optional: true
      qs:
        optional: true
  "@types/express@*":
    peerDependenciesMeta:
      body-parser:
        optional: true
      serve-static:
        optional: true
      qs:
        optional: true
  "@types/node@^14.0.0":
    peerDependencies:
      events: "*"
      querystring: "*"
      url: "*"
      util: "*"
  "@types/serve-static@*":
    dependencies:
      mime: "*"
  aws-cdk-local@1.65.8:
    dependencies:
      aws-cdk: 1.145.0
      cdk-assets: 1.145.0
      fs-extra: ^10.0.1
  aws-cdk@1.145.0:
    dependencies:
      "@aws-cdk/cloud-assembly-schema": 1.145.0
      "@aws-cdk/cloudformation-diff": 1.145.0
      "@aws-cdk/cx-api": 1.145.0
      archiver: ^5.3.0
      aws-sdk: ^1.0.0
      cdk-assets: 1.145.0
      chalk: ^4.1.2
      chokidar: ^3.5.3
      fs-extra: ^10.0.1
      minimatch: ^5.0.1
      promptly: ^3.2.0
      semver: ^7.3.5
      source-map-support: ^0.5.21
      strip-ansi: ^6.0.1
      uuid: ^8.3.2
      wrap-ansi: ^7.0.0
      yaml: ^1.10.2
  aws-cdk@1.147.0:
    dependencies:
      "@aws-cdk/cloud-assembly-schema": 1.147.0
      "@aws-cdk/cloudformation-diff": 1.147.0
      "@aws-cdk/cx-api": 1.147.0
      archiver: ^5.3.0
      aws-sdk: 2.1085.0
      cdk-assets: 1.147.0
      chalk: ^4.1.2
      chokidar: ^3.5.3
      fs-extra: ^10.0.1
      minimatch: ^5.0.1
      promptly: ^3.2.0
      semver: ^7.3.5
      source-map-support: ^0.5.21
      strip-ansi: ^6.0.1
      uuid: ^8.3.2
      wrap-ansi: ^7.0.0
      yaml: ^1.10.2
  debug@*:
    dependencies:
      supports-color: "*"
  express-openapi-validator@*:
    dependencies:
      express: "*"
  express@*:
    peerDependencies:
      body-parser: "*"
  follow-redirects@^1.14.5:
    dependencies:
      debug: "*"
  https-browserify@*:
    peerDependencies:
      url: "*"
  http-proxy-middleware@^2.0.1:
    dependencies:
      express: "*"
      url: "*"
  node-fetch@^2.6.1:
    dependencies:
      encoding: ^0.1.12
  promise-inflight@*:
    dependencies:
      bluebird: ^3.7.2
  react-scripts@*:
    peerDependencies:
      "@types/node": "*"
      "@types/react-dom": "*"
  readable-stream@*:
    dependencies:
      events: "*"
  redoc@*:
    dependencies:
      call-me-maybe: ^1.0.1
      fast-safe-stringify: ^2.1.1
      yaml: ^1.10.2
  sqlite@*:
    dependencies:
      sql-template-strings: "*"
  stream-http@*:
    peerDependencies:
      url: "*"
  styled-components@^5.3.3:
    dependencies:
      react-is: "*"


pnpMode: loose

yarnPath: .yarn/releases/yarn-3.2.2.cjs
