cacheFolder: ./.yarn/cache

nmHoistingLimits: none

nodeLinker: pnp

packageExtensions:
  "@docsearch/react@3.0.0-alpha.41":
    dependencies:
      "@algolia/client-search": ^4.11.0
  "@docusaurus/theme-search-algolia@2.0.0-beta.ff31de0ff":
    dependencies:
      prism-react-renderer: ^1.2.1
  "@material-ui/lab@^4.12.3":
    dependencies:
      "@material-ui/types": ^5.1.0
  "@types/node@^14.0.0":
    peerDependencies:
      events: "*"
      querystring: "*"
      url: "*"
      util: "*"
  aws-cdk-local@1.65.8:
    dependencies:
      aws-cdk: 1.129.0
      cdk-assets: 1.129.0
  debug@*:
    dependencies:
      supports-color: "*"
  express-openapi-validator@*:
    dependencies:
      express: "*"
  follow-redirects@^1.14.5:
    dependencies:
      debug: "*"
  https-browserify@*:
    peerDependencies:
      url: "*"
  node-fetch@^2.6.1:
    dependencies:
      encoding: ^0.1.12
  promise-inflight@*:
    dependencies:
      bluebird: ^3.7.2
  react-scripts@*:
    peerDependencies:
      "@types/node": "*"
      "@types/react-dom": "*"
  readable-stream@*:
    dependencies:
      events: "*"
  redoc@*:
    dependencies:
      call-me-maybe: ^1.0.1
      fast-safe-stringify: ^2.1.1
      yaml: ^1.10.2
  stream-http@*:
    peerDependencies:
      url: "*"
  styled-components@^5.3.3:
    dependencies:
      react-is: "*"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.1.1.cjs
