FROM golang AS builder
ADD . /code
WORKDIR /code
RUN BUILD_TAG=release make runtime

FROM scratch

COPY --from=builder /code/build/runtime_release /var/runtime/bootstrap
COPY --from=builder /code/config/tokenizer/config.yaml /config/tokenizer/
