FROM golang AS builder

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates

ADD . /code
WORKDIR /code
RUN BUILD_TAG=lambda make tokenizer

FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /code/build/tokenizer_lambda /tokenizer
COPY --from=builder /code/config/tokenizer /config/tokenizer

WORKDIR /
ENTRYPOINT ["/tokenizer"]
