app:
  stack_id: ${STACK_ID:"no-stack-id"}
analyticscollector:
  analytics_server: ${ANALYTICS_SERVER:"https://production.deployment-info.lunasec.io/record"}
  metrics:
    - tokenizeSuccess
    - tokenizeFailure
    - detokenizeSuccess
    - detokenizeFailure
    - createGrantSuccess
    - createGrantFailure
aws_gateway:
  region: us-west-2
  cloudwatch_namespace: ${CLOUDWATCH_NAMESPACE:"lunasec"}
  localstack_url: ${LOCALSTACK_URL:""}
