header:
  license:
    spdx-id: BSL-1.1
    copyright-owner: by LunaSec (owned by Refinery Labs, Inc)
    content: |
      Copyright by LunaSec (owned by Refinery Labs, Inc)

      Licensed under the Business Source License v1.1 
      (the "License"); you may not use this file except in compliance with the
      License. You may obtain a copy of the License at

      https://github.com/lunasec-io/lunasec/blob/master/licenses/BSL-LunaTrace.txt

      See the License for the specific language governing permissions and
      limitations under the License.
  paths:
    - 'lunatrace/bsl/**/*.{js,jsx,ts,tsx}'
#  these ignores do nothing, go edit the .lintstagedrc file to ignore something
  paths-ignore:
    - '.git'
    - '.idea'
    - '.idea/*'
    - '.idea/**'
    - 'licenses'
    - 'docs'
    - 'docs/**'
    - '**/dist/**'
    - 'js/**'
    - 'lunadefend/**'
    - 'tools/**'
    - 'go/build/**'
    - '**/node_modules/**'
  comment: on-failure
  license-location-threshold: 3000
