header:
  license:
    spdx-id: CC-BY-SA-4.0
    copyright-owner: by LunaSec (owned by Refinery Labs, Inc)
    content: |
        Copyright by LunaSec (owned by Refinery Labs, Inc)
  
        Licensed under the Creative Commons Attribution-ShareAlike 4.0 International
        (the "License"); you may not use this file except in compliance with the
        License. You may obtain a copy of the License at
  
        https://creativecommons.org/licenses/by-sa/4.0/legalcode
  
        See the License for the specific language governing permissions and
        limitations under the License.

  paths:
    - '*.md'
    - '**/*.md'
    - 'docs/*.{js,jsx,ts,tsx}'
    - 'docs/**/*.{js,jsx,ts,tsx}'
  #  these ignores do nothing, go edit the .lintstagedrc file to ignore something
  paths-ignore:
    - 'docs/typedoc-sidebar.js'
    - 'docs/build/**'
    - 'docs/static/**'
    - 'docs/.docusaurus/**'
    - 'docs/pages/*.md'
    - 'docs/pages/**/*.md'
    - 'docs/*.json'
    - 'docs/**/*.json'
    - 'tools/license-checker/skywalking-*/**'
    - '**/node_modules/**'
    - 'pull_request_template.md'
    - 'topics'
  comment: on-failure

  license-location-threshold: 3000
