app:
  stack_id: ${STACK_ID:"deadbeef-cafe-babe-face-8e6f524b4dce"}
  cors:
    allowed_origins:
      - ${APPLICATION_FRONT_END}
    allowed_headers:
      - Authorization
aws_gateway:
  region: us-west-2
  cloudwatch_namespace: ${CLOUDWATCH_NAMESPACE:"lunasec"}
  access_key_id: ${AWS_ACCESS_KEY_ID:""}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY:""}
  localstack_url: ${LOCALSTACK_URL:""}
  local_https_proxy: ${LOCAL_HTTPS_PROXY:""}
  ciphertext_bucket: ${CIPHERTEXT_VAULT_S3_BUCKET:"newServer"}
  table_names:
    metadata: ${METADATA_KV_TABLE:""}
    keys: ${KEYS_KV_TABLE:""}
    sessions: ${SESSIONS_KV_TABLE:""}
    grants: ${GRANTS_KV_TABLE:""}
session_controller:
  auth_providers: ${AUTH_PROVIDERS}
secure_frame_controller:
  views_path: ${SECURE_FRAME_VIEWS_PATH:"views/tokenizerbackend"}
  cdn_config: ${SECURE_FRAME_CDN_CONFIG}
  # the url that the iframe will use to call back into the tokenizer, defaults to window.location if left empty
  tokenizer_url: ${TOKENIZER_URL:""}
tokenizer:
  secret_arn: ${TOKENIZER_SECRET_ARN:""}
auth_jwt_verifier:
  # TODO (cthompson) this public key is specifically the auth provider's public key and the configuration should reflect this
  public_key: ${SESSION_PUBLIC_KEY:""}
  jwks_url: ${SESSION_JWKS_URL:""}
  jwks_kid: ${SESSION_JWKS_KID:"lunasec-signing-key"}
grant_service:
  grant_default_duration: ${GRANT_DEFAULT_DURATION:"15m"}
  grant_maximum_duration: ${GRANT_MAXIMUM_DURATION:"1h"}
metrics:
  disable: ${METRICS_DISABLED:"false"}
  provider: ${METRICS_PROVIDER:"aws_cloudwatch"}
  disable_usage_statistics: ${METRICS_DISABLE_USAGE_STATISTICS:"false"}
