# Copyright 2022 by LunaSec (owned by Refinery Labs, Inc)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: 'Merge Master Branch'
description: 'Merges the master Git branch into the current branch.'

runs:
  using: "composite"
  steps:
    # TODO: there may be a more idiomatic way to do this
    - name: Check if we should skip this build
      shell: bash
      id: job-canceller
      run: echo "::set-output name=cancelled::${{ github.event_name != 'pull_request' }}"

     # Cancel the merge copy of this build(see the matrix above) if we are not in a PR
    - name: cancelling
      uses: andymckay/cancel-action@0.2
      if: ${{ steps.job-canceller.outputs.cancelled == 'true' }}

    # Merge with master (or whatever target branch) so we are actually testing what will happen after PR merges, not just this branch
    - name: Merge target branch
      shell: bash
      run: git merge origin/${{ github.event.pull_request.base.ref }}
      if: ${{ github.event_name == 'pull_request' }}
