alter table "analysis"."manifest_dependency_edge_result" drop constraint "manifest_dependency_edge_result_vulnerability_id_manifest_dependency_edge_id_finding_source_finding_source_version_key";
alter table "analysis"."manifest_dependency_edge_result" add constraint "manifest_dependency_edge_result_vulnerability_id_manifest_dependency_edge_id_key" unique ("vulnerability_id", "manifest_dependency_edge_id");

ALTER TABLE analysis.manifest_dependency_edge_result DROP COLUMN finding_source_version;
ALTER TABLE analysis.manifest_dependency_edge_result DROP COLUMN output;
