-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE build_dependency_relationship
--     DROP COLUMN build_id;
--
-- ALTER TABLE build_dependency_relationship
--     DROP COLUMN range;
--
-- ALTER TABLE build_dependency_relationship
--     DROP COLUMN project_path;
