FROM oryd/kratos:v0.9.0

USER root

ADD config.yaml /config/config.yaml
ADD config.production.yaml /config/config.production.yaml

ADD identity.schema.json /config/identity.schema.json
ADD oidc.github.jsonnet /config/oidc.github.jsonnet
