//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"encoding/json"
	"github.com/google/uuid"
	"github.com/lunasec-io/lunasec/lunatrace/gogen/gql/types"
	"time"
)

type Package struct {
	ID                  uuid.UUID `sql:"primary_key"`
	PackageManager      types.PackageManager
	CustomRegistry      string
	Name                string
	Description         *string
	UpstreamData        json.RawMessage
	LastFailedFetch     *time.Time
	LastSuccessfulFetch *time.Time
	Internal            bool
	ReadmeText          *string
	UseCaseSummary      *string
}
