//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type ReleaseDependency struct {
	ID                  uuid.UUID `sql:"primary_key"`
	ReleaseID           uuid.UUID
	DependencyPackageID uuid.UUID
	PackageName         string
	PackageVersionQuery string
	IsDev               bool
	DependencyReleaseID uuid.UUID
}
