//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"encoding/json"
	"github.com/google/uuid"
	"time"
)

type Release struct {
	ID                     uuid.UUID `sql:"primary_key"`
	PackageID              uuid.UUID
	PublishingMaintainerID uuid.UUID
	Version                string
	UpstreamData           json.RawMessage
	ReleaseTime            *time.Time
	ObservedTime           time.Time
	BlobHash               *string
	UpstreamBlobURL        *string
	MirroredBlobURL        *string
	FetchedTime            *time.Time
}
