# Copyright 2021 by LunaSec (owned by Refinery Labs, Inc)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
getmetadata:
  post:
    tags:
      - Metadata
      - Default
    summary: Get Metadata
    operationId: getMetaData
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: './bodies.yaml#/GetMetadataRequest'
    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/GetMetadataResponse'
      '400':
        description: Bad request
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/ErrorResponse'
      '500':
        description: An Error Occured
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/ErrorResponse'
      '404':
        description: Unable to locate token
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/ErrorResponse'
