table:
  schema: public
  name: settings
object_relationships:
  - name: project
    using:
      foreign_key_constraint_on: project_id
insert_permissions:
  - role: user
    permission:
      check:
        project:
          organization:
            organization_users:
              user_id:
                _eq: X-Hasura-Real-User-Id
      columns:
        - created_at
        - id
        - pr_feedback_disabled
        - project_id
      backend_only: false
select_permissions:
  - role: service
    permission:
      columns:
        - pr_feedback_disabled
        - created_at
        - id
      filter: {}
  - role: user
    permission:
      columns:
        - created_at
        - id
        - pr_feedback_disabled
        - project_id
      filter:
        project:
          organization:
            organization_users:
              user_id:
                _eq: X-Hasura-Real-User-Id
update_permissions:
  - role: user
    permission:
      columns:
        - created_at
        - id
        - pr_feedback_disabled
        - project_id
      filter:
        project:
          organization:
            organization_users:
              user_id:
                _eq: X-Hasura-Real-User-Id
      check: null
