# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import langchain_pb2 as langchain__pb2


class LangChainStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Summarize = channel.unary_unary(
                '/langchain.LangChain/Summarize',
                request_serializer=langchain__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=langchain__pb2.SummarizeResponse.FromString,
                )
        self.CleanWebpage = channel.unary_unary(
                '/langchain.LangChain/CleanWebpage',
                request_serializer=langchain__pb2.CleanWebpageRequest.SerializeToString,
                response_deserializer=langchain__pb2.CleanWebpageResponse.FromString,
                )
        self.Chat = channel.unary_unary(
                '/langchain.LangChain/Chat',
                request_serializer=langchain__pb2.ChatRequest.SerializeToString,
                response_deserializer=langchain__pb2.ChatResponse.FromString,
                )


class LangChainServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Summarize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanWebpage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LangChainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Summarize': grpc.unary_unary_rpc_method_handler(
                    servicer.Summarize,
                    request_deserializer=langchain__pb2.SummarizeRequest.FromString,
                    response_serializer=langchain__pb2.SummarizeResponse.SerializeToString,
            ),
            'CleanWebpage': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanWebpage,
                    request_deserializer=langchain__pb2.CleanWebpageRequest.FromString,
                    response_serializer=langchain__pb2.CleanWebpageResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=langchain__pb2.ChatRequest.FromString,
                    response_serializer=langchain__pb2.ChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'langchain.LangChain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LangChain(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Summarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/langchain.LangChain/Summarize',
            langchain__pb2.SummarizeRequest.SerializeToString,
            langchain__pb2.SummarizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CleanWebpage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/langchain.LangChain/CleanWebpage',
            langchain__pb2.CleanWebpageRequest.SerializeToString,
            langchain__pb2.CleanWebpageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/langchain.LangChain/Chat',
            langchain__pb2.ChatRequest.SerializeToString,
            langchain__pb2.ChatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
