//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type PackageVersionDownloadCount struct {
	Name      string
	ReleaseID *uuid.UUID
	Version   string
	Downloads int32
	Day       time.Time
}
