name: Lint Documentation
on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'docs/blog/**'
      - 'docs/pages/**'
      - '.github/**'

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@reviewdog
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: 'docs/blog'
          fail_on_error: false
          vale_flags: 'docs/pages'
