name: LunaTrace

# This workflow posts hasura changes as a comment.
on:
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/**'
      - 'lunatrace/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install tools
        uses: yokawasa/action-setup-kube-tools@v0.8.0
        with:
          setup-tools: |
            yq
          yq: "4.16.2"
      - name: Build
        run: |-
          set -x
          (cd lunatrace/bsl/logger && yarn run compile)
          (cd lunatrace/bsl/common && yarn run compile)
          (cd lunatrace/bsl/backend && yarn run compile)
          (cd lunatrace/bsl/frontend && yarn run build:docker)

      - run: docker-compose up -d
        working-directory: lunatrace/bsl

      - uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: 'http://localhost:8080/'
          responseCode: '200,500'
          timeout: 2000
          interval: 500

      - run: |-

          (cd lunatrace/bsl/hasura && (
            function hasura() {
              docker-compose exec -T -w /hasura graphql-engine bash -c "HASURA_GRAPHQL_ENDPOINT=\"http://localhost:8080\" hasura-cli $*"
            }
            hasura md ic list
            hasura md ic status
            
            curl -vvv localhost:8080
          ) || true)
          
      - run: docker-compose logs
        working-directory: lunatrace/bsl
