name: LunaTrace

# This workflow posts hasura changes as a comment.
on:
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/**'
      - 'lunatrace/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install tools
        uses: yokawasa/action-setup-kube-tools@v0.8.0
        with:
          setup-tools: |
            yq
          yq: "4.16.2"
      - name: Build
        run: |-
          set -x
          #(cd lunatrace/bsl/logger && yarn run compile)
          #(cd lunatrace/bsl/common && yarn run compile)
          #(cd lunatrace/bsl/backend && yarn run compile)
          #(cd lunatrace/bsl/frontend && yarn run build:docker)

      - run: docker-compose up -d
        working-directory: lunatrace/bsl

      - name: Integration Test
        run: |-
          timeout 120 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080)" != "404" ]]; do sleep 1; done' || false
          
          (cd lunatrace/bsl/hasura && (
            function hasura() {
              npx --yes hasura-cli --skip-update-check $@
            }
            set -x
            hasura md ic list >> /tmp/hasura_ic
            hasura md ic status || (cat /tmp/hasura_ic > /tmp/comment)
          ) || true)
          
      - run: docker-compose logs
        working-directory: lunatrace/bsl

      - name: Check comment
        run: cat /tmp/comment | grep -qE '.' && echo '::set-output name=found::true'
        id: check-comment

      - id: get-comment-body
        run: |
          body="$(cat /tmp/comment)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: "Hasura Inconsistencies Detected"

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ steps.check-comment.outputs.found == 'true' || steps.fc.outputs.comment-id }}
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |-
            # Hasura Inconsistencies Detected
            Please check that the metadata can be applied with the migrations against a clean database.
            ```
            ${{ steps.get-comment-body.outputs.body }}
            ```
          edit-mode: replace
