name: LunaTrace

# This workflow posts hasura changes as a comment.
on:
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/**'
      - 'lunatrace/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install tools
        uses: yokawasa/action-setup-kube-tools@v0.8.0
        with:
          setup-tools: |
            yq
          yq: "4.16.2"
      - name: Build
        run: |-
          set -x
          (cd lunatrace/bsl/logger && yarn run compile)
          (cd lunatrace/bsl/common && yarn run compile)
          (cd lunatrace/bsl/backend && yarn run compile)
          (cd lunatrace/bsl/frontend && yarn run build:docker)
      - run: |-
          (cd lunatrace/bsl && docker-compose up -d)
          tools/service-scripts/wait-for-it.sh -h localhost -p 8080 -t 120
          
          (cd lunatrace/bsl/hasura && (
            HASURA="npx --yes hasura-cli --skip-update-check"
            $HASURA md ic list
            $HASURA md ic status
            
            curl -vvv localhost:8080
          ) || true)
          
          (cd lunatrace/bsl && docker-compose logs)
