name: Super Linter

on:
  pull_request:
    branches: [master, main]

jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      - uses: snow-actions/sparse-checkout@v1.1.0
        with:
          patterns: |
            .github
            lunatrace/bsl/hasura
#            go
#            lunatrace
#            guides
#            tools
#            go.mod
#            go.sum

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          #VALIDATE_GITHUB_ACTIONS: true
          #VALIDATE_BASH: true
          #VALIDATE_MARKDOWN: true
          #VALIDATE_YAML: true
          #VALIDATE_GO: true
          VALIDATE_SQLFLUFF: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
